Lesson4
rattvol/ReactHomeWork pull request #3
Opened 2024-07-05 12:36 UTC by rattvol

2024-07-05 15:35 UTC, zubkov7 commented on components/customHook/useCounter.jsx
обычно для хуков делают отдельную папку hooks внутри папки конкретного компонента или в src

2024-07-05 15:37 UTC, zubkov7 commented on components/reviewForm/reviewForm.jsx
> +        <input
также можно добавить min max на инпут

2024-07-05 15:39 UTC, zubkov7 commented on components/reviewForm/reviewForm.jsx
> +      <button className="inputBlock" onClick={() => dispatch("")}>
лучше создать конкретный action - clear

2024-07-05 15:40 UTC, zubkov7 commented on package.json
> +    "eslint-plugin-react-refresh": "^0.4.7",
до этого не рабал hot reload? по идее в vite должно быть внутри зашито

2024-07-05 15:40 UTC, zubkov7 commented on .eslintrc.cjs
> +  plugins: ["react-refresh"],
почему решили prettier убрать?

2024-07-05 15:44 UTC, zubkov7 requested changes

2024-07-05 15:44 UTC, zubkov7 commented on components/app/app.jsx
> +    const element = document.getElementById("progressBar");
в реакте так не взаимодействуем с элементами

давайте создадим отдельный компонент ProgressBar и в него унесем логику эффекта

можно добавить состояние percentage и менять его в эффекте и уже через пропсы добавлять нужный стиль
там можно менять стиль нужного элемента

2024-07-05 15:44 UTC, zubkov7 commented on components/app/app.jsx
> +  });
также необходимо добавлять зависимости, без массива зависимостей это будет выполнятся на каждый ререндер

2024-07-06 04:43 UTC, rattvol commented on package.json
> +    "eslint-plugin-react-refresh": "^0.4.7",
До этого не корректно работал eslint, не реагировал на настройки конфига и не проверял именования хуков. Добавил на всякий случай. Hot reload работал.

2024-07-07 03:05 UTC, rattvol commented on components/app/app.jsx
> +    const element = document.getElementById("progressBar");
Исправил

2024-07-07 09:43 UTC, zubkov7 commented on package.json
> +    "eslint-plugin-react-refresh": "^0.4.7",
последнюю версию vite использовать при создании? смотрю, что изначально он должен был быть в package.json

вообще этот пакет не должен влиять на именование хуков, возможно конфиг неправильно указали в ide ?

2024-07-07 09:45 UTC, zubkov7 commented on .eslintrc.cjs
почему решили убрать плагины?

2024-07-07 09:47 UTC, zubkov7 commented on components/app/app.jsx
> -import { useState } from "react";
useEffect не используется, это должен подсвечивать линтер

можно его прогнать: pnpm run lint

2024-07-07 09:47 UTC, zubkov7 commented on components/restaurant/useCounter/useCounter
забыли добавить расширение файла .ts

2024-07-07 09:48 UTC, zubkov7 commented on components/restaurant/useCounter/useCounter
> +  const min = 0;
обычно константы выносим из функции, чтобы они каждый раз не пересоздавались. С примитивами не страшно, но с объектами будет каждый раз новая ссылка

2024-07-07 12:50 UTC, rattvol commented on .eslintrc.cjs
До удаления плагина plugin:react/jsx-runtime не работала настройка конфига "react/react-in-jsx-scope": "off". Линт требовал поключать React в каждом компоненте. Остальные изменения в процессе поиска решения подключал-отключал. Но вроде то, что получилось, особо на функционал не влияет. EsLint и Prettier работают. Ошибки пропускаю скорее по невнимательности, т.к. дз приходится делать практически на ходу.

2024-07-07 20:33 UTC, zubkov7 commented on .eslintrc.cjs
очень странно, нужно будет посмотреть проблему, потому что из коробки должно работать. С ДЗ не связано, но все же

2024-07-07 20:35 UTC, zubkov7 commented on components/progressBar/progressBar.jsx
> +    return window.removeEventListener("scroll", () =>
нам тут нужно вернуть именно функцию, которая вызовется при cleanup и сделает необходимую логику - https://react.dev/reference/react/useEffect#parameters

2024-07-08 08:06 UTC, merged